name: Check Versions
on:
 workflow_dispatch:
 
permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read
  
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Front
      uses: actions/checkout@v4
    - name: Scanner
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.0"
      
    - name: Get Front Version
      id: front_version
      run: |
        echo "FRONT_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
    - name: Clone Back
      run: |
        git clone --depth 1 https://github.com/horaciovasconcellos/back.git back

    - name: Get Back Version
      id: back_version
      run: |
        echo "BACK_VERSION=$(cat back/package.json | jq -r .version)" >> $GITHUB_ENV

    - name: Print Versions
      run: |
        echo "Front Version: $FRONT_VERSION"
        echo "Back Version: $BACK_VERSION"
